"""
core/services/hybrid_answer_service.py

Answer generation pipeline:
    1. Ollama  (local free model — primary, same as question generation)
    2. FLAN-T5 (local trained model — fallback)
    3. OpenRouter (API fallback — last resort)
"""

import requests
import json
import os

from core.services.flan_answer_service import generate_flan_answer
from core.openrouter_service import ask_openrouter
from core.services.ollama_question_service import (
    is_ollama_available,
    OLLAMA_HOST,
    OLLAMA_MODEL,
    OLLAMA_TIMEOUT,
)

_MIN_ANSWER_LENGTH = 20
_GARBAGE_PATTERNS = [
    "i don't know", "i do not know", "no answer",
    "n/a", "undefined", "none", "<pad>", "<unk>",
]

def _is_good_answer(text: str) -> bool:
    if not text or len(text.strip()) < _MIN_ANSWER_LENGTH:
        return False
    lower = text.lower().strip()
    if any(pat in lower for pat in _GARBAGE_PATTERNS):
        return False
    return True


def _generate_ollama_answer(question: str) -> str | None:
    """Generate expected answer using local Ollama model."""

    prompt = (
        f"You are an expert technical interviewer.\n"
        f"Provide a concise but complete expected answer "
        f"for this interview question. Answer in 3-5 sentences maximum.\n"
        f"Do not repeat the question. Just give the answer directly.\n\n"
        f"Question: {question}\n\n"
        f"Expected Answer:"
    )

    response = requests.post(
        url=f"{OLLAMA_HOST}/api/generate",
        headers={"Content-Type": "application/json"},
        data=json.dumps({
            "model":  OLLAMA_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature":    0.4,   # lower = more factual answers
                "repeat_penalty": 1.2,
                "num_predict":    200,   # answers don't need to be long
            }
        }),
        timeout=OLLAMA_TIMEOUT
    )
    response.raise_for_status()
    result   = response.json()
    raw_text = result.get("response", "").strip()

    if not raw_text:
        return None

    # Clean up any "Expected Answer:" prefix Ollama sometimes echoes back
    for prefix in ["Expected Answer:", "Answer:", "A:"]:
        if raw_text.startswith(prefix):
            raw_text = raw_text[len(prefix):].strip()

    return raw_text if raw_text else None


# ─────────────────────────────────────────────────────────────────
def generate_answer(question: str) -> str:
    """
    Main entry point called by answer_generator.py

    Pipeline: Ollama → FLAN-T5 → OpenRouter
    """

    # ── STAGE 1: OLLAMA ───────────────────────────────
    try:
        if is_ollama_available():
            print("[INFO] Trying Ollama for answer generation...")
            ollama_answer = _generate_ollama_answer(question)

            if ollama_answer and _is_good_answer(ollama_answer):
                print("[SUCCESS] Answer generated by Ollama")
                return ollama_answer.strip()

            print("[INFO] Ollama answer weak — trying FLAN-T5")
        else:
            print("[INFO] Ollama not available — trying FLAN-T5")

    except Exception as e:
        print(f"[WARN] Ollama answer generation failed: {e}")

    # ── STAGE 2: FLAN-T5 ──────────────────────────────
    try:
        print("[INFO] Trying FLAN-T5 for answer generation...")
        flan_answer = generate_flan_answer(question)

        if _is_good_answer(flan_answer):
            print("[SUCCESS] Answer generated by FLAN-T5")
            return flan_answer.strip()

        print("[INFO] FLAN-T5 answer weak — falling back to OpenRouter")

    except Exception as e:
        print(f"[WARN] FLAN-T5 failed: {e}")

    # ── STAGE 3: OPENROUTER ───────────────────────────
    print("[INFO] Using OpenRouter for answer generation...")
    try:
        prompt = (
            f"You are an expert technical interviewer.\n"
            f"Provide a concise but complete expected answer "
            f"for this interview question.\n\n"
            f"Question: {question}\n\n"
            f"Expected Answer:"
        )
        answer = ask_openrouter(prompt)
        if answer:
            print("[SUCCESS] Answer generated by OpenRouter")
            return answer.strip()

    except Exception as e:
        print(f"[WARN] OpenRouter failed: {e}")

    # ── SAFETY NET ────────────────────────────────────
    return (
        "The candidate should explain the core concepts "
        "related to this question clearly with practical examples."
    )